all: Point.cpp Common.cpp Jarvis.cpp GrahamStack.cpp Graham.cpp median.cpp Kirkpatrick.cpp main.cpp
	g++ -o final Point.cpp Common.cpp Jarvis.cpp GrahamStack.cpp Graham.cpp median.cpp Kirkpatrick.cpp main.cpp -g 


    
    
